server:
  port: 84


spring:
  application:
    name: cloudalibaba-sentinel-order
  cloud:
    nacos:
      discovery:
        # 服务中心注册地址
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8090
        port: 8710  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: cloudalibaba-sentinel-order
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'

service-url:
  nacos-user-service: http://nacos-payment-provider
  #对Feign的支持
feign:
  sentinel:
    enabled: true






