server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com #修改host文件后的实例名称
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上获取服务的注册信息
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/