server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  datasource:
    username: root
    password: l1itdhjaoiqw32kwqe$5asasd*a21
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  cloud:
    zookeeper:
      discovery:
        instancePort: ${server.port} #端口号
        enabled: true
        register: true
      connect-string: 127.0.0.1:2181



  logging:
    level:
      com.cloud.demo.microprovider.mapper:  debug


